// Generated by gencpp from file offb_msgs/ServoNum.msg
// DO NOT EDIT!


#ifndef OFFB_MSGS_MESSAGE_SERVONUM_H
#define OFFB_MSGS_MESSAGE_SERVONUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offb_msgs
{
template <class ContainerAllocator>
struct ServoNum_
{
  typedef ServoNum_<ContainerAllocator> Type;

  ServoNum_()
    : num(0)  {
    }
  ServoNum_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef uint16_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::offb_msgs::ServoNum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offb_msgs::ServoNum_<ContainerAllocator> const> ConstPtr;

}; // struct ServoNum_

typedef ::offb_msgs::ServoNum_<std::allocator<void> > ServoNum;

typedef boost::shared_ptr< ::offb_msgs::ServoNum > ServoNumPtr;
typedef boost::shared_ptr< ::offb_msgs::ServoNum const> ServoNumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offb_msgs::ServoNum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offb_msgs::ServoNum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offb_msgs::ServoNum_<ContainerAllocator1> & lhs, const ::offb_msgs::ServoNum_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offb_msgs::ServoNum_<ContainerAllocator1> & lhs, const ::offb_msgs::ServoNum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offb_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::offb_msgs::ServoNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offb_msgs::ServoNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb_msgs::ServoNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb_msgs::ServoNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb_msgs::ServoNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb_msgs::ServoNum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offb_msgs::ServoNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0285aea93c08847f409c58db5e8d9137";
  }

  static const char* value(const ::offb_msgs::ServoNum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0285aea93c08847fULL;
  static const uint64_t static_value2 = 0x409c58db5e8d9137ULL;
};

template<class ContainerAllocator>
struct DataType< ::offb_msgs::ServoNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offb_msgs/ServoNum";
  }

  static const char* value(const ::offb_msgs::ServoNum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offb_msgs::ServoNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 num\n"
;
  }

  static const char* value(const ::offb_msgs::ServoNum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offb_msgs::ServoNum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoNum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offb_msgs::ServoNum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offb_msgs::ServoNum_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFB_MSGS_MESSAGE_SERVONUM_H
